const PRODUCTS = [
  {
    id: "heritage-black-shirt",
    name: "Heritage Black Shirt",
    category: "Formal Wear",
    price: 2499,
    originalPrice: 3199,
    popularity: 96,
    newest: 8,
    badge: "Best Seller",
    image: "images/products/heritage-black-shirt.jpg",
    gallery: ["images/products/heritage-black-shirt.jpg", "images/hero-tailored-presence.jpg", "images/the-rich-look-logo.jpeg"],
    galleryAlt: ["Heritage Black Shirt premium cotton blend - front view", "Heritage Black Shirt structured collar detail", "TheRich Look brand crest logo"],
    colors: ["Matte Black", "Rich Gold"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    description: "A crisp black statement shirt crafted for refined evenings, formal occasions, and confident everyday dressing.",
    details: ["Premium cotton blend", "Structured collar", "Tailored regular fit", "Gold-tone finishing inspiration"]
  },
  {
    id: "royal-ivory-shirt",
    name: "Royal Ivory Shirt",
    category: "Formal Wear",
    price: 2299,
    originalPrice: 2899,
    popularity: 90,
    newest: 7,
    badge: "New Arrival",
    image: "images/products/royal-ivory-shirt.jpg",
    gallery: ["images/products/royal-ivory-shirt.jpg", "images/hero-tailored-presence.jpg", "images/the-rich-look-logo.jpeg"],
    galleryAlt: ["Royal Ivory Shirt elegant formal wear - front view", "Tailored formal dressing inspiration", "TheRich Look brand crest logo"],
    colors: ["Warm Ivory", "Soft Beige"],
    sizes: ["S", "M", "L", "XL"],
    description: "An elegant ivory essential for ceremonies, dinners, and sophisticated business dressing.",
    details: ["Soft hand feel", "Breathable weave", "Refined button placket", "Pairs with charcoal tailoring"]
  },
  {
    id: "charcoal-tailored-trouser",
    name: "Charcoal Tailored Trouser",
    category: "Everyday Essentials",
    price: 2799,
    originalPrice: 3499,
    popularity: 88,
    newest: 6,
    badge: "Essential",
    image: "images/products/charcoal-tailored-trouser.jpg",
    gallery: ["images/products/charcoal-tailored-trouser.jpg", "images/hero-tailored-presence.jpg", "images/the-rich-look-logo.jpeg"],
    galleryAlt: ["Charcoal Tailored Trouser premium fit - front view", "Tailored silhouette for business and occasions", "TheRich Look brand crest logo"],
    colors: ["Charcoal", "Matte Black"],
    sizes: ["30", "32", "34", "36", "38"],
    description: "A versatile trouser with a clean silhouette, made for office hours, celebrations, and evening plans.",
    details: ["Sharp front crease", "Comfort waistband", "Tapered profile", "Formal-casual versatility"]
  },
  {
    id: "midnight-bandhgala",
    name: "Midnight Bandhgala Jacket",
    category: "Premium Men's Fashion",
    price: 6999,
    originalPrice: 8499,
    popularity: 94,
    newest: 9,
    badge: "Signature",
    image: "images/products/midnight-bandhgala.jpg",
    gallery: ["images/products/midnight-bandhgala.jpg", "images/hero-tailored-presence.jpg", "images/the-rich-look-logo.jpeg"],
    galleryAlt: ["Midnight Bandhgala Jacket occasion wear - front view", "Structured shoulder formal jacket detail", "TheRich Look brand crest logo"],
    colors: ["Midnight", "Charcoal"],
    sizes: ["M", "L", "XL", "XXL"],
    description: "A commanding occasion jacket inspired by Indian elegance and contemporary menswear restraint.",
    details: ["Mandarin collar", "Structured shoulder", "Premium lining", "Occasion-ready finish"]
  },
  {
    id: "beige-linen-overshirt",
    name: "Beige Linen Overshirt",
    category: "Casual Wear",
    price: 2599,
    originalPrice: 3299,
    popularity: 81,
    newest: 5,
    badge: "Weekend Edit",
    image: "images/products/beige-linen-overshirt.jpg",
    gallery: ["images/products/beige-linen-overshirt.jpg", "images/hero-tailored-presence.jpg", "images/the-rich-look-logo.jpeg"],
    galleryAlt: ["Beige Linen Overshirt relaxed layer - front view", "Casual premium menswear styling", "TheRich Look brand crest logo"],
    colors: ["Soft Beige", "Warm Ivory"],
    sizes: ["S", "M", "L", "XL"],
    description: "A relaxed layer with quiet richness, built for Mysuru weekends, travel, and polished casual dressing.",
    details: ["Linen-look texture", "Layer-friendly fit", "Utility pockets", "Soft beige tone"]
  },
  {
    id: "monarch-polo",
    name: "Monarch Knit Polo",
    category: "Casual Wear",
    price: 1899,
    originalPrice: 2399,
    popularity: 85,
    newest: 4,
    badge: "Popular",
    image: "images/products/monarch-polo.jpg",
    gallery: ["images/products/monarch-polo.jpg", "images/hero-tailored-presence.jpg", "images/the-rich-look-logo.jpeg"],
    galleryAlt: ["Monarch Knit Polo premium quality - front view", "Ribbed collar casual-smart styling", "TheRich Look brand crest logo"],
    colors: ["Matte Black", "Rich Gold"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    description: "A premium polo for men who prefer casualwear with structure, texture, and presence.",
    details: ["Knit-inspired texture", "Ribbed collar", "Smart casual fit", "Easy day-to-night styling"]
  },
  {
    id: "signature-blazer",
    name: "Signature Charcoal Blazer",
    category: "Formal Wear",
    price: 7999,
    originalPrice: 9999,
    popularity: 99,
    newest: 10,
    badge: "Best Seller",
    image: "images/products/signature-blazer.jpg",
    gallery: ["images/products/signature-blazer.jpg", "images/hero-tailored-presence.jpg", "images/the-rich-look-logo.jpeg"],
    galleryAlt: ["Signature Charcoal Blazer premium formal wear - front view", "Structured lapel timeless silhouette", "TheRich Look brand crest logo"],
    colors: ["Charcoal", "Matte Black"],
    sizes: ["38", "40", "42", "44"],
    description: "A confident blazer with a timeless profile, designed to anchor formal wardrobes with understated luxury.",
    details: ["Structured lapel", "Soft shoulder balance", "Premium lining", "Elegant charcoal finish"]
  },
  {
    id: "essential-tee",
    name: "Ivory Essential Tee",
    category: "Everyday Essentials",
    price: 1299,
    originalPrice: 1699,
    popularity: 76,
    newest: 3,
    badge: "Core",
    image: "images/products/essential-tee.jpg",
    gallery: ["images/products/essential-tee.jpg", "images/hero-tailored-presence.jpg", "images/the-rich-look-logo.jpeg"],
    galleryAlt: ["Ivory Essential Tee premium everyday wear - front view", "Modern crew neck clean styling", "TheRich Look brand crest logo"],
    colors: ["Warm Ivory", "Matte Black"],
    sizes: ["S", "M", "L", "XL"],
    description: "A soft, elevated everyday tee for clean layering and minimal premium styling.",
    details: ["Dense cotton feel", "Modern crew neck", "Clean drape", "Everyday premium comfort"]
  },
  {
    id: "con001-hm-conscious",
    name: "H&M Concious",
    category: "Casual Wear",
    price: 749,
    originalPrice: 1299,
    popularity: 60,
    newest: 5,
    badge: "Cotton",
    image: "images/products/con001-hm-conscious.jpeg",
    gallery: ["images/products/con001-hm-conscious-1.jpeg", "images/products/con001-hm-conscious-2.jpeg", "images/products/con001-hm-conscious-3.jpeg", "images/products/con001-hm-conscious.jpeg"],
    galleryAlt: ["H&M Concious relaxed cotton trousers front view", "H&M Concious cotton trousers close-up detail shot", "H&M Concious collection display in multiple colors and sizes", "H&M Concious premium cotton trousers product shot"],
    colors: ["Cream", "Light Khaki", "Black", "Navy Blue", "Ash Gray", "Khaki Green"],
    sizes: ["30", "32", "34", "36", "38"],
    description: "Relaxed cotton fit for casual wear.",
    details: ["100% cotton", "Relaxed fit", "Machine wash cold"]
  },
  {
    id: "skn003-skin-it-arrow-plain",
    name: "SKIN IT - Arrow Plain",
    category: "Casual Wear",
    price: 499,
    originalPrice: 999,
    popularity: 50,
    newest: 4,
    badge: "Oversize",
    image: "images/products/skn003-skin-it-arrow-plain.jpeg",
    gallery: [
      "images/products/skn003-skin-it-arrow-plain-1.jpeg",
      "images/products/skn003-skin-it-arrow-plain-2.jpeg",
      "images/products/skn003-skin-it-arrow-plain.jpeg"
    ],
    galleryAlt: [
      "SKIN IT - Arrow Plain oversized arrow graphic tee front view",
      "SKIN IT - Arrow Plain close-up of back print and fabric texture",
      "SKIN IT - Arrow Plain product flat lay showing available colors"
    ],
    colors: ["Cream", "Black", "Olive green", "Brown"],
    sizes: ["S", "M", "L", "XL"],
    description: "Oversized graphic tee, streetwear t-shirt, men's boxy fit shirt, geometric arrow t-shirt, urban clothing, graphic tee, back print t-shirt.",
    details: ["Oversized fit", "100% cotton", "Machine wash cold"]
  },
  {
    id: "skn002-skin-it-jordan",
    name: "SKIN IT - Jordan",
    category: "Casual Wear",
    price: 599,
    originalPrice: 999,
    popularity: 40,
    newest: 4,
    badge: "Oversize",
    image: "images/products/skn002-skin-it-jordan.jpeg",
    gallery: [
      "images/products/skn002-skin-it-jordan-1.jpeg",
      "images/products/skn002-skin-it-jordan-2.jpeg",
      "images/products/skn002-skin-it-jordan.jpeg"
    ],
    galleryAlt: [
      "SKIN IT - Jordan graphic tee orange and space blue front view",
      "SKIN IT - Jordan neon green and brick red colorways flat lay",
      "SKIN IT - Jordan product group display"
    ],
    colors: ["Orange", "Space Blue", "Neon Green", "Brick Red"],
    sizes: ["S", "M", "L", "XL"],
    description: "Level up your streetwear game with this vibrant Jordan graphic tee.",
    details: ["Oversized fit", "100% cotton", "Machine wash cold"]
  }
];

const BRAND = {
  name: "TheRich Look",
  tagline: "Dress Beyond Ordinary",
  phonePrimary: "+91 7406708408",
  phoneSecondary: "+91 8971513765",
  address: "Sri Krishnadevaraya Road, Nayantara, 2nd Main Road, Mysuru - 570008, Karnataka, India",
  instagram: "@therichlook_24"
};
