const PRODUCTS = [
  {
    id: "heritage-black-shirt",
    name: "Heritage Black Shirt",
    category: "Formal Wear",
    price: 2499,
    originalPrice: 3199,
    popularity: 96,
    newest: 8,
    badge: "Best Seller",
    image: "images/products/heritage-black-shirt.jpg",
    gallery: ["images/products/heritage-black-shirt.jpg", "images/hero-tailored-presence.jpg", "images/the-rich-look-logo.jpeg"],
    colors: ["Matte Black", "Rich Gold"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    description: "A crisp black statement shirt crafted for refined evenings, formal occasions, and confident everyday dressing.",
    details: ["Premium cotton blend", "Structured collar", "Tailored regular fit", "Gold-tone finishing inspiration"]
  },
  {
    id: "royal-ivory-shirt",
    name: "Royal Ivory Shirt",
    category: "Formal Wear",
    price: 2299,
    originalPrice: 2899,
    popularity: 90,
    newest: 7,
    badge: "New Arrival",
    image: "images/products/royal-ivory-shirt.jpg",
    gallery: ["images/products/royal-ivory-shirt.jpg", "images/hero-tailored-presence.jpg", "images/the-rich-look-logo.jpeg"],
    colors: ["Warm Ivory", "Soft Beige"],
    sizes: ["S", "M", "L", "XL"],
    description: "An elegant ivory essential for ceremonies, dinners, and sophisticated business dressing.",
    details: ["Soft hand feel", "Breathable weave", "Refined button placket", "Pairs with charcoal tailoring"]
  },
  {
    id: "charcoal-tailored-trouser",
    name: "Charcoal Tailored Trouser",
    category: "Everyday Essentials",
    price: 2799,
    originalPrice: 3499,
    popularity: 88,
    newest: 6,
    badge: "Essential",
    image: "images/products/charcoal-tailored-trouser.jpg",
    gallery: ["images/products/charcoal-tailored-trouser.jpg", "images/hero-tailored-presence.jpg", "images/the-rich-look-logo.jpeg"],
    colors: ["Charcoal", "Matte Black"],
    sizes: ["30", "32", "34", "36", "38"],
    description: "A versatile trouser with a clean silhouette, made for office hours, celebrations, and evening plans.",
    details: ["Sharp front crease", "Comfort waistband", "Tapered profile", "Formal-casual versatility"]
  },
  {
    id: "midnight-bandhgala",
    name: "Midnight Bandhgala Jacket",
    category: "Premium Men's Fashion",
    price: 6999,
    originalPrice: 8499,
    popularity: 94,
    newest: 9,
    badge: "Signature",
    image: "images/products/midnight-bandhgala.jpg",
    gallery: ["images/products/midnight-bandhgala.jpg", "images/hero-tailored-presence.jpg", "images/the-rich-look-logo.jpeg"],
    colors: ["Midnight", "Charcoal"],
    sizes: ["M", "L", "XL", "XXL"],
    description: "A commanding occasion jacket inspired by Indian elegance and contemporary menswear restraint.",
    details: ["Mandarin collar", "Structured shoulder", "Premium lining", "Occasion-ready finish"]
  },
  {
    id: "beige-linen-overshirt",
    name: "Beige Linen Overshirt",
    category: "Casual Wear",
    price: 2599,
    originalPrice: 3299,
    popularity: 81,
    newest: 5,
    badge: "Weekend Edit",
    image: "images/products/beige-linen-overshirt.jpg",
    gallery: ["images/products/beige-linen-overshirt.jpg", "images/hero-tailored-presence.jpg", "images/the-rich-look-logo.jpeg"],
    colors: ["Soft Beige", "Warm Ivory"],
    sizes: ["S", "M", "L", "XL"],
    description: "A relaxed layer with quiet richness, built for Mysuru weekends, travel, and polished casual dressing.",
    details: ["Linen-look texture", "Layer-friendly fit", "Utility pockets", "Soft beige tone"]
  },
  {
    id: "monarch-polo",
    name: "Monarch Knit Polo",
    category: "Casual Wear",
    price: 1899,
    originalPrice: 2399,
    popularity: 85,
    newest: 4,
    badge: "Popular",
    image: "images/products/monarch-polo.jpg",
    gallery: ["images/products/monarch-polo.jpg", "images/hero-tailored-presence.jpg", "images/the-rich-look-logo.jpeg"],
    colors: ["Matte Black", "Rich Gold"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    description: "A premium polo for men who prefer casualwear with structure, texture, and presence.",
    details: ["Knit-inspired texture", "Ribbed collar", "Smart casual fit", "Easy day-to-night styling"]
  },
  {
    id: "signature-blazer",
    name: "Signature Charcoal Blazer",
    category: "Formal Wear",
    price: 7999,
    originalPrice: 9999,
    popularity: 99,
    newest: 10,
    badge: "Best Seller",
    image: "images/products/signature-blazer.jpg",
    gallery: ["images/products/signature-blazer.jpg", "images/hero-tailored-presence.jpg", "images/the-rich-look-logo.jpeg"],
    colors: ["Charcoal", "Matte Black"],
    sizes: ["38", "40", "42", "44"],
    description: "A confident blazer with a timeless profile, designed to anchor formal wardrobes with understated luxury.",
    details: ["Structured lapel", "Soft shoulder balance", "Premium lining", "Elegant charcoal finish"]
  },
  {
    id: "essential-tee",
    name: "Ivory Essential Tee",
    category: "Everyday Essentials",
    price: 1299,
    originalPrice: 1699,
    popularity: 76,
    newest: 3,
    badge: "Core",
    image: "images/products/essential-tee.jpg",
    gallery: ["images/products/essential-tee.jpg", "images/hero-tailored-presence.jpg", "images/the-rich-look-logo.jpeg"],
    colors: ["Warm Ivory", "Matte Black"],
    sizes: ["S", "M", "L", "XL"],
    description: "A soft, elevated everyday tee for clean layering and minimal premium styling.",
    details: ["Dense cotton feel", "Modern crew neck", "Clean drape", "Everyday premium comfort"]
  },
  {
    id: "con001-hm-conscious",
    name: "H&M Concious",
    category: "Casual Wear",
    price: 749,
    originalPrice: 1299,
    popularity: 60,
    newest: 5,
    badge: "Cotton",
    image: "images/products/con001-hm-conscious.jpg",
    gallery: ["images/products/con001-hm-conscious.jpg"],
    colors: ["Cream", "Light Khaki", "Black", "Navy Blue", "Ash Gray", "Khaki Green"],
    sizes: ["30", "32", "34", "36", "38"],
    description: "Relaxed cotton fit for casual wear.",
    details: ["100% cotton", "Relaxed fit", "Machine wash cold"]
  }
];

const BRAND = {
  name: "TheRich Look",
  tagline: "Dress Beyond Ordinary",
  phonePrimary: "+91 7406708408",
  phoneSecondary: "+91 8971513765",
  address: "Sri Krishnadevaraya Road, Nayantara, 2nd Main Road, Mysuru - 570008, Karnataka, India",
  instagram: "@therichlook_24"
};
